x-base: &base
  build:
    context: .
    args:
      LOCAL_UID: ${LOCAL_UID}
      LOCAL_GID: ${LOCAL_GID}
      ROS_DISTRO: ${ROS_DISTRO}
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID}
      USER_NAME: ${USER_NAME}

  image: ${IMAGE_NAME}
  container_name: ${PARENT_DIR_NAME}

  network_mode: host
  privileged: true
  shm_size: 2g

  user: "${LOCAL_UID}:${LOCAL_GID}"
  group_add:
    - dialout
    - audio
    - video

  environment:
    USER_NAME: ${USER_NAME}
    CONTAINER_NAME: ${PARENT_DIR_NAME}
    GH_TOKEN: ${GITHUB_TOKEN}
    DISPLAY: ${DISPLAY}
    PULSE_SERVER: unix:/run/user/${LOCAL_UID}/pulse/native

  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - /run/user/${LOCAL_UID}/pulse:/run/user/${LOCAL_UID}/pulse
    - /run/udev:/run/udev:ro
    - /dev:/dev
    - ../src:/home/${USER_NAME}/colcon_ws/src
    - ${HOME}/.ssh:/home/${USER_NAME}/.ssh:ro
    - ${HOME}/.gitconfig:/home/${USER_NAME}/.gitconfig

  stdin_open: true
  tty: true

services:
  ros2:
    <<: *base
    profiles: ["cpu"]

  ros2_gpu:
    <<: *base
    gpus: all
    profiles: ["gpu"]