COLOR_WHITE = "#FFFFFF"
COLOR_BG_LIGHT = "#F5F7FA"
COLOR_TEXT = "#333333"

COLOR_PRIMARY = "#2196F3"
COLOR_PRIMARY_DARK = "#1565C0"
COLOR_PRIMARY_LIGHT = "#BBDEFB"

COLOR_SUCCESS = "#4CAF50"
COLOR_WARNING = "#FF9800"
COLOR_ERROR = "#F44336"
COLOR_INFO = "#03A9F4"

COLOR_HOVER = "#E3F2FD"
COLOR_DISABLED = "#ECEFF1"
COLOR_DISABLED_TEXT = "#90A4AE"
COLOR_CONTAINER_ROW_ALT = "#FAFBFC"
COLOR_BORDER = "#E0E0E0"

PADDING_SMALL = 4
PADDING_MEDIUM = 8
PADDING_LARGE = 12
BORDER_RADIUS = 6
BUTTON_WIDTH = 8
BUTTON_HEIGHT = 1